### ISSUE TITLE
MNE-SKIN -- NetLogo 4.1

### ISSUE THREAD

**Issue by gepr** [InnovationNetworks/skin#6]
Seems to execute fine with NetLogo-5.1, 5.2.1, and 5.3.1 with a pop-up notice. It might be relatively simple to run a regression test from 5.3.1 against 4.1.

Fails with NetLogo 6.0.1 with the following error:
`
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at scala.io.BufferedSource.mkString(BufferedSource.scala:94)
	at org.nlogo.fileformat.AbstractNLogoFormat.$anonfun$sections$2(NLogoFormat.scala:40)
	at scala.util.Success.flatMap(Try.scala:247)
	at org.nlogo.fileformat.AbstractNLogoFormat.sections(NLogoFormat.scala:39)
	at org.nlogo.fileformat.AbstractNLogoFormat.sections$(NLogoFormat.scala:35)
	at org.nlogo.fileformat.NLogoFormat.sections(NLogoFormat.scala:17)
	at org.nlogo.api.ModelFormat.load(ModelFormat.scala:53)
	at org.nlogo.api.ModelFormat.load$(ModelFormat.scala:51)
	at org.nlogo.fileformat.NLogoFormat.load(NLogoFormat.scala:17)
	at org.nlogo.api.FormatterPair.load(ModelLoader.scala:26)
	at org.nlogo.api.ModelLoader.readModel(ModelLoader.scala:60)
	at org.nlogo.api.ModelLoader.readModel$(ModelLoader.scala:57)
	at org.nlogo.api.ConfigurableModelLoader.readModel(ModelLoader.scala:90)
	at org.nlogo.workspace.OpenModelFromURI$.readModel(OpenModel.scala:85)
	at org.nlogo.workspace.OpenModelFromURI$.readModel(OpenModel.scala:83)
	at org.nlogo.workspace.OpenModel.runOpenModelProcess(OpenModel.scala:49)
	at org.nlogo.workspace.OpenModel.runOpenModelProcess$(OpenModel.scala:34)
	at org.nlogo.workspace.OpenModelFromURI$.runOpenModelProcess(OpenModel.scala:83)
	at org.nlogo.workspace.OpenModelFromURI$.apply(OpenModel.scala:93)
	at org.nlogo.app.FileManager.$anonfun$openModelURI$1(FileManager.scala:287)
	at org.nlogo.app.FileManager.$anonfun$loadModel$2(FileManager.scala:314)
	at org.nlogo.swing.ModalProgressTask$Worker.run(ModalProgressTask.scala:69)
`

**Comment by micrology** [comment]
I did a bit of investigation and this error is caused by the encoding of the program file.  Changing it to UTF-8 improves matters.  But to read it into NL6, one then has to convert the code into NL 5, and then into NL 6 (going straight from NL 4 to 6 gives an error about a BUTTON reader).  However, then converting from NL5 to NL6 gives a warning about an automatic syntax conversion error that I haven’t yet had time to track down.

Nigel



________________________________
Professor Nigel Gilbert, CBE, ScD, FREng, FAcSS, Professor of Sociology,
University of Surrey, Guildford GU2 7XH, UK. +44 (0)1483 689173
